// src/components/AddProductForm.jsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import "../styles/AddProductForm.css";

export default function AddProductForm({ onCancel, onProductAdded }) {
  const navigate = useNavigate();

  const [products, setProducts] = useState([]);
  const [loadingProducts, setLoadingProducts] = useState(false);
  const [errorProducts, setErrorProducts] = useState("");

  // Form state
  const [formData, setFormData] = useState({
    productName: "",
    productDescription: "",
    basicPricing: "",
    discountType: null, // Changed from "" to null
    productSKU: "",
    productBarcode: "",
    productQuantity: "",
    productWeight: "",
    productHeight: "",
    productLength: "",
    productWidth: "",
    productCategory: "",
    productTags: "",
    productStatus: "",
    image_url: [],
    isPhysical: false,
  });

  const [image, setImage] = useState(null);
  const [imagePreview, setImagePreview] = useState(null);
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);
  const [popup, setPopup] = useState({ show: false, type: "", message: "" });

  const defaultImage = "https://cdn-icons-png.flaticon.com/512/7486/7486744.png";

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        setLoadingProducts(true);
        const res = await axios.get("https://acc-in-touch-1.onrender.com/api/Product");
        setProducts(res.data);
      } catch (err) {
        console.error("Error fetching products:", err);
        setErrorProducts("Failed to load products");
      } finally {
        setLoadingProducts(false);
      }
    };

    fetchProducts();
  }, []);

  // SKU is generated by backend, so we don't need to generate it here

  // Show popup
  const showPopup = (type, message) => {
    setPopup({ show: true, type, message });
  };

  // Close popup
  const closePopup = () => {
    const { type } = popup;
    setPopup({ show: false, type: "", message: "" });
    if (type === "success") {
      navigate("/ProductManagement");
    }
  };

  // Handle input changes
  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: type === "checkbox" ? checked : value,
    }));
    if (errors[name]) {
      setErrors((prev) => ({ ...prev, [name]: "" }));
    }
  };

  // Image upload
  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        setErrors((prev) => ({
          ...prev,
          image_url: "Image size should be less than 5MB",
        }));
        return;
      }
      setImage(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setImagePreview(reader.result);
      };
      reader.readAsDataURL(file);
      setErrors((prev) => ({ ...prev, image_url: "" }));
    }
  };

  // Validate form
  const validateForm = () => {
    const newErrors = {};

    if (!formData.productName.trim()) {
      newErrors.productName = "Product name is required";
    }

    if (!formData.basicPricing || parseFloat(formData.basicPricing) <= 0) {
      newErrors.basicPricing = "Valid base price is required";
    }

    if (!formData.productQuantity || parseInt(formData.productQuantity) < 0) {
      newErrors.productQuantity = "Valid quantity is required";
    }

    if (!formData.productCategory) {
      newErrors.productCategory = "Product category is required";
    }

    if (!formData.productStatus) {
      newErrors.productStatus = "Product status is required";
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  // Handle form submission
  const handleSubmit = async () => {
    // Validate before submitting
    if (!validateForm()) {
      showPopup("error", "Please fill in all required fields correctly.");
      return;
    }

    try {
      setLoading(true);
      const data = new FormData();

      // Append all form fields
      Object.entries(formData).forEach(([key, value]) => {
        if (value === null || value === undefined) return;
        if (Array.isArray(value)) return;

        // Skip empty strings for optional fields (like discountType)
        if (value === "" && (key === "discountType" || key === "productTags" || key === "productDescription" || key === "productBarcode")) {
          return; // Don't send empty strings for these fields
        }

        if (typeof value === "boolean" || typeof value === "number") {
          data.append(key, String(value));
        } else {
          data.append(key, value);
        }
      });

      // Append image file if selected
      if (image) {
        data.append("image_url", image);
      }

      // Debug: Log what's being sent
      console.log("📤 Sending data:");
      for (let pair of data.entries()) {
        console.log(pair[0], pair[1]);
      }

      // POST to backend API
      const res = await axios.post(
        "https://acc-in-touch-1.onrender.com/api/Product",
        data,
        { 
          headers: { "Content-Type": "multipart/form-data" },
          timeout: 30000 // 30 second timeout
        }
      );

      console.log("✅ Product Created:", res.data);

      if (onProductAdded) onProductAdded(res.data);

      showPopup("success", "Product added successfully!");
    } catch (error) {
      console.error("❌ Error creating product:", error);
      
      // More detailed error message
      let errorMessage = "Failed to add product.";
      
      if (error.response) {
        // Server responded with error
        errorMessage = error.response.data?.message || 
                      error.response.data?.error ||
                      `Server error: ${error.response.status}`;
        console.error("Server response:", error.response.data);
      } else if (error.request) {
        // Request made but no response
        errorMessage = "No response from server. Please check your connection.";
      } else {
        // Error setting up request
        errorMessage = error.message;
      }
      
      showPopup("error", errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const goToProductManagement = () => {
    navigate("/ProductManagement");
  };

  // Helper to calculate final price
  const finalPriceDisplay = () => {
    const base = parseFloat(formData.basicPricing);
    const discount = parseFloat(formData.discountType);
    if (isNaN(base)) return "₹0.00";
    if (isNaN(discount) || discount === 0) return `₹${base.toFixed(2)}`;
    const finalPrice = base * (1 - discount / 100);
    return `₹${finalPrice.toFixed(2)}`;
  };

  return (
    <div className="addProductadd-product-container full-page">
      {/* Popup Modal */}
      {popup.show && (
        <div className="addProductpopup-overlay" onClick={closePopup}>
          <div className="addProductpopup-modal" onClick={(e) => e.stopPropagation()}>
            <div className={`addProductpopup-icon ${popup.type}`}>
              {popup.type === "success" ? (
                <svg width="48" height="48" viewBox="0 0 24 24" fill="none">
                  <path d="M20 6L9 17L4 12" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              ) : (
                <svg width="48" height="48" viewBox="0 0 24 24" fill="none">
                  <path d="M12 8V12M12 16H12.01M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              )}
            </div>
            <h3 className="addProductpopup-title">
              {popup.type === "success" ? "Success!" : "Error"}
            </h3>
            <p className="addProductpopup-message">{popup.message}</p>
            <button className="addProductpopup-button" onClick={closePopup}>
              {popup.type === "success" ? "Go to Products" : "Close"}
            </button>
          </div>
        </div>
      )}

      {/* Top bar */}
      <div className="addProductadd-product-top top-v2">
        <div className="addProductbreadcrumb">
          <span
            className="addProductcrumb-link"
            onClick={goToProductManagement}
            role="link"
            tabIndex={0}
          >
            Product
          </span>
          <span className="addProductcrumb-sep">›</span>
          <span className="addProductcrumb-current">Add Product</span>
        </div>

        <div className="addProducttop-buttons">
          <button 
            className="addProductbtn cancel outlined" 
            onClick={onCancel || goToProductManagement}
          >
            <span className="addProductbtn-text">Cancel</span>
          </button>

          <button 
            className="addProductbtn add-product filled" 
            type="button"
            onClick={handleSubmit}
            disabled={loading}
          >
            <span className="addProductbtn-text">{loading ? "Adding..." : "Add Product"}</span>
          </button>
        </div>
      </div>

      {/* Main Layout */}
      <div className="addProductadd-product-layout">
        {/* Left Column */}
        <div className="addProductadd-left">
          {/* General Info */}
          <section className="addProductcard">
            <h3 className="addProductcard-title">General Information</h3>

            <div className="addProductform-row">
              <label className="addProductlabel">
                Product Name <span className="addProductrequired">*</span>
              </label>
              <input 
                className={`addProductinput ${errors.productName ? 'error' : ''}`}
                name="productName"
                value={formData.productName}
                onChange={handleChange}
                placeholder="Type product name here…"
              />
              {errors.productName && (
                <span className="addProducterror-text">{errors.productName}</span>
              )}
            </div>

            <div className="addProductform-row">
              <label className="addProductlabel">Product Description</label>
              <textarea
                className="addProducttextarea"
                name="productDescription"
                value={formData.productDescription}
                onChange={handleChange}
                placeholder="Type product description here…"
              />
            </div>
          </section>

          {/* Media */}
          <section className="addProductcard">
            <h3 className="addProductcard-title">Media</h3>
            <div className="addProductmedia-dropzone">
              <div className="addProductimage-preview-box">
                <img
                  src={imagePreview || defaultImage}
                  alt="Preview"
                  className={imagePreview ? "addProductuploaded-image" : "addProductdefault-image"}
                />
              </div>

              <div className="addProductmedia-note">
                Drag and drop image here, or click add image
              </div>

              <input
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                style={{ display: "none" }}
                id="image-upload"
              />
              <label htmlFor="image-upload" className="addProductbtn outline small">
                Add Image
              </label>
              {errors.image_url && (
                <span className="addProducterror-text">{errors.image_url}</span>
              )}
            </div>
          </section>

          {/* Pricing */}
          <section className="addProductcard">
            <h3 className="addProductcard-title">Pricing</h3>

            <div className="addProductform-row">
              <label className="addProductlabel">
                Base Price <span className="addProductrequired">*</span>
              </label>
              <input 
                className={`addProductinput no-arrows ${errors.basicPricing ? 'error' : ''}`}
                name="basicPricing"
                type="number"
                value={formData.basicPricing}
                onChange={handleChange}
                placeholder="₹ Type base price here…"
                step="0.01"
                min="0"
              />
              {errors.basicPricing && (
                <span className="addProducterror-text">{errors.basicPricing}</span>
              )}
            </div>

            <div className="addProductform-row two">
              <div className="addProductinput-wrapper">
                <label className="addProductlabel">Discount Percentage</label>
                <select 
                  className="addProductselect"
                  name="discountType"
                  value={formData.discountType}
                  onChange={handleChange}
                >
                  <option value="">No Discount</option>
                  <option value="5">5%</option>
                  <option value="10">10%</option>
                  <option value="15">15%</option>
                  <option value="20">20%</option>
                  <option value="25">25%</option>
                  <option value="30">30%</option>
                  <option value="35">35%</option>
                  <option value="40">40%</option>
                  <option value="45">45%</option>
                  <option value="50">50%</option>
                </select>
              </div>

              {formData.basicPricing && (
                <div className="addProductinput-wrapper">
                  <label className="addProductlabel">Final Price</label>
                  <div className="addProductfinal-price">
                    {finalPriceDisplay()}
                  </div>
                </div>
              )}
            </div>
          </section>

          {/* Inventory */}
          <section className="addProductcard">
            <h3 className="addProductcard-title">Inventory</h3>
            <div className="addProductform-row three">
              <div className="addProductinput-wrapper">
                <label className="addProductlabel">
                  SKU <span className="addProductrequired">*</span>
                </label>
                <input 
                  className={`addProductinput ${errors.productSKU ? 'error' : ''}`}
                  name="productSKU"
                  value={formData.productSKU || ""}
                  placeholder="Auto-generated"
                  readOnly
                />
                <span className="addProducthelper-text">Auto-generated based on name & category</span>
              </div>

              <div className="addProductinput-wrapper">
                <label className="addProductlabel">Barcode</label>
                <input 
                  className="addProductinput"
                  name="productBarcode"
                  value={formData.productBarcode}
                  onChange={handleChange}
                  placeholder="Barcode"
                />
              </div>

              <div className="addProductinput-wrapper">
                <label className="addProductlabel">
                  Quantity <span className="addProductrequired">*</span>
                </label>
                <input 
                  className={`addProductinput no-arrows ${errors.productQuantity ? 'error' : ''}`}
                  name="productQuantity"
                  type="number"
                  value={formData.productQuantity}
                  onChange={handleChange}
                  placeholder="Quantity"
                  min="0"
                />
                {errors.productQuantity && (
                  <span className="addProducterror-text">{errors.productQuantity}</span>
                )}
              </div>
            </div>
          </section>

          {/* Shipping */}
          <section className="addProductcard">
            <h3 className="addProductcard-title">Shipping</h3>
            <div className="addProductshipping-toggle">
              <input 
                type="checkbox" 
                id="physical"
                name="isPhysical"
                checked={formData.isPhysical}
                onChange={handleChange}
              />
              <label htmlFor="physical">This is a physical product</label>
            </div>
            {formData.isPhysical && (
              <div className="addProductform-row four" style={{ marginTop: 12 }}>
                <div className="addProductinput-wrapper">
                  <label className="addProductlabel">Weight (g)</label>
                  <input 
                    className="addProductinput no-arrows"
                    name="productWeight"
                    type="text"
                    value={formData.productWeight}
                    onChange={handleChange}
                    placeholder="Weight"
                  />
                </div>

                <div className="addProductinput-wrapper">
                  <label className="addProductlabel">Height (cm)</label>
                  <input 
                    className="addProductinput no-arrows"
                    name="productHeight"
                    type="text"
                    value={formData.productHeight}
                    onChange={handleChange}
                    placeholder="Height"
                  />
                </div>

                <div className="addProductinput-wrapper">
                  <label className="addProductlabel">Length (cm)</label>
                  <input 
                    className="addProductinput no-arrows"
                    name="productLength"
                    type="text"
                    value={formData.productLength}
                    onChange={handleChange}
                    placeholder="Length"
                  />
                </div>

                <div className="addProductinput-wrapper">
                  <label className="addProductlabel">Width (cm)</label>
                  <input 
                    className="addProductinput no-arrows"
                    name="productWidth"
                    type="text"
                    value={formData.productWidth}
                    onChange={handleChange}
                    placeholder="Width"
                  />
                </div>
              </div>
            )}
          </section>
        </div>

        {/* Right Sidebar */}
        <div className="addProductadd-right">
          <section className="addProductcard sidebar-card">
            <h3 className="addProductcard-title">Category</h3>

            <label className="addProductlabel">
              Product Category <span className="addProductrequired">*</span>
            </label>
            <select 
              className={`addProductselect ${errors.productCategory ? 'error' : ''}`}
              name="productCategory"
              value={formData.productCategory}
              onChange={handleChange}
              required
            >
              <option value="">Select a category</option>
              <option value="hairBows">Hair Bows</option>
              <option value="claws">Claws</option>
              <option value="scrunchies">Scrunchies</option>
              <option value="Earrings">Earrings</option>
            </select>
            {errors.productCategory && (
              <span className="addProducterror-text">{errors.productCategory}</span>
            )}

            <label className="addProductlabel" style={{ marginTop: 16 }}>Product Tags</label>
            <input 
              className="addProductinput"
              name="productTags"
              value={formData.productTags}
              onChange={handleChange}
              placeholder="e.g., colorful, trending"
            />
            <div className="addProducthelper-text">Separate tags with commas</div>

            <label className="addProductlabel" style={{ marginTop: 16 }}>
              Product Status <span className="addProductrequired">*</span>
            </label>
            <select 
              className={`addProductselect ${errors.productStatus ? 'error' : ''}`}
              name="productStatus"
              value={formData.productStatus}
              onChange={handleChange}
            >
              <option value="">Select status</option>
              <option value="inStock">In Stock</option>
              <option value="lowStock">Low Stock</option>
              <option value="outOfStock">Out of Stock</option>
              <option value="discontinued">Discontinued</option>
              <option value="draft">Draft</option>
            </select>
            {errors.productStatus && (
              <span className="addProducterror-text">{errors.productStatus}</span>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}